name: Auto Email Sender

on:
  workflow_dispatch:       # Allows manual or API triggering
  schedule:
    - cron: '*/5 * * * *'   # Optional: every 5 minutes (if enabled)

jobs:
  send_mail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run email script
        env:
          SMTP_DILSHAD: ${{ secrets.SMTP_DILSHAD }}
          SMTP_NANA: ${{ secrets.SMTP_NANA }}
          SMTP_GAURAV: ${{ secrets.SMTP_GAURAV }}
          SMTP_INFO: ${{ secrets.SMTP_INFO }}
          SMTP_SALES: ${{ secrets.SMTP_SALES }}
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          TRACKING_BACKEND_URL: https://email-tracker-3ce5.onrender.com
        run: |
          echo "$GOOGLE_JSON" > credentials.json
          python main.py
