name: Scheduled Email Sender

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send_mail:
    runs-on: ubuntu-22.04  # More stable than ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run email sender
        env:
          SMTP_DILSHAD: ${{ secrets.SMTP_DILSHAD }}
          SMTP_NANA: ${{ secrets.SMTP_NANA }}
          SMTP_GAURAV: ${{ secrets.SMTP_GAURAV }}
          SMTP_INFO: ${{ secrets.SMTP_INFO }}
          SMTP_SALES: ${{ secrets.SMTP_SALES }}
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          TRACKING_BACKEND_URL: https://auto-email-scheduler.onrender.com
          SHEET_ID: ${{ secrets.SHEET_ID }}       # ← Add this line
        run: |
          echo "$GOOGLE_JSON" > credentials.json
          python main.py
